# Generated by Django 2.1.1 on 2018-11-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.ImageField(upload_to='usuarios')),
                ('sexo', models.NullBooleanField()),
            ],
        ),
    ]
