# Generated by Django 2.0.8 on 2019-05-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20181114_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='correo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='telefono2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
