# Generated by Django 2.0.8 on 2019-06-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20190602_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
