# Generated by Django 2.0.8 on 2018-09-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='tipocc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipocc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipocc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='tipocc',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
