# Generated by Django 2.0.8 on 2018-09-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0002_auto_20180917_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientesdireccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='gestionapp.Cliente')),
            ],
            options={
                'ordering': ['direccion'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='clientesdireccion',
            unique_together={('codigo', 'direccion')},
        ),
    ]
