# Generated by Django 2.0.8 on 2018-09-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0003_auto_20180923_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientesdireccion',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='clientesdireccion',
            old_name='codigo',
            new_name='codunico',
        ),
        migrations.AlterUniqueTogether(
            name='clientesdireccion',
            unique_together={('codunico', 'id')},
        ),
    ]
