# Generated by Django 2.0.8 on 2018-09-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0004_auto_20180923_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientesdireccion',
            old_name='codunico',
            new_name='master',
        ),
        migrations.AlterUniqueTogether(
            name='clientesdireccion',
            unique_together={('master', 'id')},
        ),
    ]
