# Generated by Django 2.0.8 on 2018-09-23 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0005_auto_20180923_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientesdireccion',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientesdirecciones', to='gestionapp.Cliente'),
        ),
    ]
