# Generated by Django 2.1.1 on 2018-09-24 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0006_auto_20180923_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcotizacion',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionapp.Mcotizacion'),
        ),
    ]
