# Generated by Django 2.0.8 on 2018-09-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0010_auto_20180924_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcotizacion',
            name='correoruc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
