# Generated by Django 2.0.8 on 2018-09-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0011_mcotizacion_correoruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcotizacion',
            name='unidadtransporte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
