# Generated by Django 2.0.8 on 2018-09-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0012_mcotizacion_unidadtransporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='npasajeros',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
