# Generated by Django 2.0.8 on 2019-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0014_auto_20180926_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcotizacion',
            name='horafin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcotizacion',
            name='horaini',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='horafin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='horaini',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='horafin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='horaini',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dcotizacion',
            name='desunimed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dcotizacion',
            name='unimed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dgasto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dgasto',
            name='desunimed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dgasto',
            name='unimed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dguia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dguia',
            name='desunimed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='dguia',
            name='unimed',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
