# Generated by Django 2.0.8 on 2019-02-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0015_auto_20190227_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcotizacion',
            name='horafin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcotizacion',
            name='horaini',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
