# Generated by Django 2.0.8 on 2019-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0018_auto_20190301_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcotizacion',
            name='lugdestino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mcotizacion',
            name='lugorigen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
