# Generated by Django 2.0.8 on 2019-03-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0019_auto_20190301_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcotizacion',
            name='opcviaje',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dgasto',
            name='opcviaje',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dguia',
            name='opcviaje',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
