# Generated by Django 2.0.8 on 2019-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0020_auto_20190301_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcotizacion',
            name='opcviaje',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
