# Generated by Django 2.0.8 on 2019-03-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0024_auto_20190313_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
