# Generated by Django 2.0.8 on 2019-04-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0025_auto_20190314_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='unidad'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='unidad'),
        ),
    ]
