# Generated by Django 2.0.8 on 2019-04-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0026_auto_20190410_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='unidad'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='unidad'),
        ),
    ]
