# Generated by Django 2.0.8 on 2019-04-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0027_auto_20190410_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigo',
            field=models.CharField(max_length=30),
        ),
    ]
