# Generated by Django 2.0.8 on 2019-04-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0028_auto_20190424_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descolor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='desruc',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='desunimed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='genero',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='modelo',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='talla',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='umdsali',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='umdsaliconv',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unimed',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
