# Generated by Django 2.0.8 on 2019-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0031_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dgasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dguia',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
