# Generated by Django 2.0.8 on 2019-05-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0032_auto_20190503_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
