# Generated by Django 2.0.8 on 2019-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0034_dmateriales_mmateriales'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialesEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
