# Generated by Django 2.0.8 on 2019-05-03 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0035_materialesestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmateriales',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='gestionapp.Mmateriales'),
        ),
    ]
