# Generated by Django 2.0.8 on 2019-05-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0036_auto_20190503_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='preciocosto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioventa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='preciocosto',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='precioventa',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
