# Generated by Django 2.0.8 on 2019-05-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0038_auto_20190508_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcotizacion',
            name='precio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dgasto',
            name='precio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dguia',
            name='precio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='dmateriales',
            name='precio',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=15),
        ),
    ]
