# Generated by Django 2.0.8 on 2019-05-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0039_auto_20190508_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcotizacion',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dgasto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dguia',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dmateriales',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
    ]
