# Generated by Django 2.0.8 on 2019-05-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0042_auto_20190509_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='preciocosto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precioventa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='preciocosto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='material',
            name='precioventa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
