# Generated by Django 2.0.8 on 2019-05-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0044_auto_20190512_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcotizacion',
            name='tc_dolares',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='mcotizacion',
            name='tc_euros',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='mcotizacion',
            name='tc_yen',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='mmateriales',
            name='tc_dolares',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='mmateriales',
            name='tc_euros',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='mmateriales',
            name='tc_yen',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=8, null=True),
        ),
    ]
