# Generated by Django 2.0.8 on 2019-05-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0045_auto_20190520_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='desmoneventa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='monedaventa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='desmonecompra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='monedacompra',
            field=models.IntegerField(default=0),
        ),
    ]
