# Generated by Django 2.0.8 on 2019-06-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0046_auto_20190522_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stockmin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='material',
            name='stockmin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
