# Generated by Django 2.0.8 on 2019-06-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0047_auto_20190610_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='stockmax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='material',
            name='stockmax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
