# Generated by Django 2.0.8 on 2019-07-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0048_auto_20190610_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='color',
            field=models.CharField(choices=[('0', 'Blanco'), ('1', 'Negro'), ('2', 'Rojo'), ('3', 'Amarillo'), ('4', 'Azul')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='color',
            field=models.CharField(choices=[('0', 'Blanco'), ('1', 'Negro'), ('2', 'Rojo'), ('3', 'Amarillo'), ('4', 'Azul')], default=0, max_length=50),
        ),
    ]
