# Generated by Django 2.0.8 on 2019-07-27 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0050_auto_20190725_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='plmovpersonal',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='gestionapp.Plaempleados'),
        ),
    ]
