# Generated by Django 2.0.8 on 2019-07-31 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0051_plmovpersonal_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plmovpersonal',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movpersonal', to='gestionapp.Plaempleados'),
        ),
    ]
