# Generated by Django 2.0.8 on 2019-08-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0052_auto_20190731_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plaregistrosemanal',
            new_name='Pltareosemanal',
        ),
    ]
