# Generated by Django 2.0.8 on 2019-08-23 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0054_remove_pltareosemanal_codemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pldatosreloj',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movreloj', to='gestionapp.Pltareosemanal'),
        ),
    ]
