# Generated by Django 2.0.8 on 2019-09-06 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0055_pldatosreloj_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plactacte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('codemp', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('codctacte', models.CharField(blank=True, max_length=15, null=True)),
                ('desctacte', models.CharField(blank=True, max_length=15, null=True)),
                ('cc', models.CharField(blank=True, max_length=100, null=True)),
                ('descc', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaini', models.DateField(blank=True, null=True)),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('fechagen', models.DateField(blank=True, null=True)),
                ('turno', models.CharField(blank=True, max_length=15, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctacte', to='gestionapp.Plaempleados')),
            ],
        ),
    ]
