# Generated by Django 2.0.8 on 2019-09-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0056_plactacte'),
    ]

    operations = [
        migrations.AddField(
            model_name='plmovpersonal',
            name='destipoctacte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plmovpersonal',
            name='tipoctacte',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
