# Generated by Django 2.0.8 on 2019-09-26 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0060_auto_20190925_1943'),
        ('gestionapp', '0057_auto_20190910_0036'),
    ]

    operations = [
    ]
