# Generated by Django 2.0.8 on 2019-09-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0060_auto_20190925_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='prorecetas',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
