# Generated by Django 2.0.8 on 2019-10-01 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0062_auto_20190930_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proproduccion',
            old_name='cantidad',
            new_name='totcant',
        ),
        migrations.RenameField(
            model_name='prorecetas',
            old_name='cantidad',
            new_name='totcant',
        ),
    ]
