# Generated by Django 2.0.8 on 2019-10-04 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0061_merge_20190926_0111'),
        ('gestionapp', '0063_auto_20190930_2053'),
    ]

    operations = [
    ]
