# Generated by Django 2.0.8 on 2019-10-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionapp', '0064_plmovpersonal_destipoctacte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plmovpersonal',
            name='destipoctacte',
        ),
    ]
